const names = [
    "Joela Haker",
    "Martainn Reven",
    "Petronella Dello",
    "Netta Jore",
    "Lynelle Kennedy",
    "Jude Bills",
    "Allen MacKessock",
    "Elbertina Duchesne",
    "Ermentrude Downey",
    "Arleen Denyer",
    "Gasparo Simonsson",
    "Natasha Rebichon",
    "Conrado Bachelar",
    "Darrelle Nunnery",
    "Robby Lydon",
    "Deeann Franklyn",
    "Francesco Sleeny",
    "Clifford Hardiker",
    "Chancey Garthside",
    "Claudette Loweth",
    "Cristabel Trehearne",
    "Hollis Ransfield",
    "Nat Caslin",
    "Agata Blum",
    "Carmita Winning",
    "Elsworth Oakley",
    "Waiter Kissick",
    "Marijn Dalliston",
    "Patrick Swiffen",
    "Brier Impy",
    "Keefe Dries",
    "Onofredo McIlriach",
    "Catarina Vedeneev",
    "Brit Hegges",
    "Charla Szymanowski",
    "Jamesy Vidgeon",
    "Howie Jacobowits",
    "Farra Moorerud",
    "Allen De Pero",
    "Malchy Cowper",
    "Lula Dickey",
    "Mahmoud Erratt",
    "Salmon Pittem",
    "Althea Barsby",
    "Gwen Learoid",
    "Adolf Mafham",
    "Brinn Petchell",
    "Emili Lillicrap",
    "Orlan Troke",
    " "
];

const thoughts = [
  "Curabitur in libero ut massa volutpat convallis.",
  "Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
  "Donec semper sapien a libero. Nam dui.",
  "Ut at dolor quis odio consequat varius. Integer ac leo.",
  "Ut tellus. Nulla ut erat id mauris vulputate elementum.",
  "Suspendisse potenti.",
  "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.",
  "Morbi vel lectus in quam fringilla rhoncus.",
  "In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
  "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  "Mauris lacinia sapien quis libero.",
  "Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
  "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.",
  "Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
  "In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.",
  "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.",
  "Nulla mollis molestie lorem. Quisque ut erat.",
  "Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.",
  "Nullam sit amet turpis elementum ligula vehicula consequat.",
  "Morbi vel lectus in quam fringilla rhoncus.",
  "Integer ac leo.",
  "Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
  "Duis mattis egestas metus.",
  "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.",
  "Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
  "Curabitur gravida nisi at nibh.",
  "Aenean fermentum.",
  "Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.",
  "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.",
  "Nulla mollis molestie lorem. Quisque ut erat.",
  "Duis mattis egestas metus.",
  "Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.",
  "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.",
  "Etiam pretium iaculis justo. In hac habitasse platea dictumst.",
  "Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.",
  "Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.",
  "Nulla ac enim.",
  "Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.",
  "Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.",
  "Nunc nisl.",
  "Ut tellus.",
  "Pellentesque eget nunc.",
  "Ut tellus.",
  "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.",
  "Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
  "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.",
  "Nulla nisl. Nunc nisl.",
  "Etiam justo. Etiam pretium iaculis justo.",
  "Proin interdum mauris non ligula pellentesque ultrices.",
  "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus."
];

const reactions = [
  "morbi porttitor lorem",
  "lobortis convallis tortor risus dapibus",
  "nibh fusce",
  "luctus et ultrices",
  "morbi vel",
  "dolor sit amet",
  "hac habitasse platea",
  "platea dictumst aliquam",
  "odio condimentum id",
  "turpis adipiscing lorem vitae mattis",
  "viverra eget congue",
  "ac est lacinia nisi venenatis",
  "ut nunc vestibulum ante ipsum",
  "pulvinar sed nisl",
  "lobortis sapien sapien",
  "orci luctus",
  "pellentesque eget nunc donec quis",
  "elementum ligula vehicula",
  "neque libero convallis",
  "donec quis",
  "phasellus in felis",
  "lectus aliquam sit amet diam",
  "consequat lectus in",
  "amet diam",
  "magna at",
  "massa id",
  "et ultrices posuere cubilia",
  "cras pellentesque volutpat",
  "in sagittis dui",
  "suspendisse potenti nullam porttitor lacus",
  "ante ipsum primis",
  "justo sit",
  "interdum venenatis turpis enim",
  "vel dapibus at diam nam",
  "blandit nam nulla integer pede",
  "nibh ligula nec sem duis",
  "eros vestibulum",
  "quam nec dui luctus",
  "in leo maecenas pulvinar",
  "in imperdiet et commodo",
  "maecenas ut",
  "id luctus nec molestie",
  "duis at velit eu est",
  "purus phasellus in",
  "euismod scelerisque quam turpis adipiscing",
  "felis fusce",
  "quis libero nullam sit",
  "lectus pellentesque eget nunc donec",
  "dictumst etiam faucibus cursus",
  "integer ac leo pellentesque"
];

const randomizer = (array) => array[Math.floor(Math.random() * array.length)];

const userRandomizer = () =>
  randomizer(names);
